apiVersion: 0.1.0
meta:
  version: 0.1.0
  name: instance-name
  topic: output-topic
  type: connector-main-source
  secrets:
   - name: SECRET_NAME
custom:
  interval_sec: 61
  secret_example_param: ${{ secrets.SECRET_NAME }}

