[package]
name = "connector-hello-source"
group = "hello-world"
version = "0.1.0"
apiVersion = "0.1.0"
fluvio = "0.21"
description = "Sample Connector Source"
license = "Apache-2.0"
visibility = "private"

[direction]
source = true

[deployment]
binary = "connector-main"

[custom.properties.interval_sec]
title = "interval_sec"
description = "Update interval in seconds"
type = "integer"
